Token=90091783780966024:0:iJfFW6zTCKaMMfQPeVqWucfEy2R0ua
URI=wss://d1.nandbox.net:5020/nandbox/api/
DownloadServer=https://d1.nandbox.net:5020/nandbox/download/
UploadServer=https://d1.nandbox.net:5020/nandbox/upload/